$(function() {
    var state = 0;
    var language =
        [
            /////////////////////////////////////////首页翻译/////////////////////////////////////////////////////////////////
                                                                                        //中文
            {
                "title":"首页",
                "top_0": "现在咨询享受9折优惠",
                "top_1":"立即咨询",
                "top_2":"获取帮助",
                "top_3": "职业介绍",
                "top_4":"信息反馈",
                "top_5": "语言选择",
                "top_6":"中文",
                "top_7": "English",
                "top_8": "日语",
                "top_9": "韩语",
                "banner_0":"重庆市渝北区中渝爱都会",
                "banner_1":"中国，重庆，重庆市",
                "banner_2":"微信：",
                "banner_3":"18184079966",
                "banner_4":"问题帮助",
                "banner_5":"首页",
                "banner_6":"关于公司",
                "banner_7":"团队风采",
                "banner_8":"联系我们",
                "banner_9":"首页",
                "banner_10":"关于公司",
                "banner_11":"团队风采",
                "banner_12":"关于我们",
                "shuffling_0":"魔法棒智能帮助你",
                "shuffling_1":"节约个人时间和",
                "shuffling_2": "降低企业成本。",
                "shuffling_3": "魔法棒智能业务主题每天都在成长",
                "shuffling_4":"感谢相信我们。",
                "shuffling_5": "了解更多",
                "shuffling_6":"魔法棒智能全方位",
                "shuffling_7": "保障你的数据和",
                "shuffling_8":"您的隐私。",
                "shuffling_9":"魔法棒智能业务主题每天都在成长",
                "shuffling_10": "感谢相信我们。",
                "shuffling_11":"了解更多",
                "shuffling_12": "专业为企业",
                "shuffling_13":"提供智能软件与",
                "shuffling_14": "自动化编程服务。",
                "shuffling_15":"魔法棒智能业务主题每天都在成长",
                "shuffling_16": "感谢相信我们",
                "shuffling_17":"了解更多",
                "shuffling_18":"我们致力于为个人与企业提供自动化软件工具定制服务，这是我们事业的方向",
                "5_banner_0":"模拟电脑操作",
                "5_banner_1":"帮助完成你所需要完成的电脑操作步骤，自动、可控、高效的完成你所需要的目标。",
                "5_banner_2":" 网络数据抓取",
                "5_banner_3":"对网络数据进行获取、整理、分析，减少人力操作和时间成本。",
                "5_banner_4":"解决方案制定",
                "5_banner_5":"针对个人和企业特有的情况提供合适的解决方案。",
                "5_banner_6":"数据定向分析",
                "5_banner_7":"对现有数据进行可视化整理和分析挖掘。",
                "5_banner_8":"自动化软件设计",
                "5_banner_9":"为个人或者企业定制其需要的自动化程序",
                "about_0":"关于我们",
                "about_1":"感谢信任魔法棒智能",
                "about_2": "我们的目标很简单，给用户最简单最直接的解决方案",
                "about_3": "我们需要让用户感受到，软件定制和自动化编程没有那么复杂，最重要的目的是让用户以最简单的方式得到解决方案，让用户明白我们在干什么，我们要干什么。",
                "about_4":"我们以最简洁最透明的方式呈现给客户，人人皆可轻易的进入自动化时代，让时间变得更宝贵，让个人和企业专注于思考更需要重视的事情，希望通过高效率和高自动化的流程和服务，为社会发展尽自己的微薄之力。",
                "about_5": "覃于澎",
                "about_6":"高效",
                "about_7": "直面问题",
                "about_8":"专业",
                "about_9":"解决问题",
                "about_10": "透明",
                "about_11": "过程跟踪",
                "shuffling_central_0":"何事之成",
                "shuffling_central_1":"我们最近的项目",
                "shuffling_central_2": "更多服务",
                "shuffling_central_3": "APP上线监控",
                "shuffling_central_4":"详细信息",
                "shuffling_central_5": "客户想知道自己的应用程序在全球上线情况和是否有相似性的APP，我们为其量身定制了一款大数据获取解决方案，使用户获得自己想要的数据",
                "shuffling_central_6":"了解更多",
                "shuffling_central_7": "APP上线监控",
                "shuffling_central_8":"详细信息",
                "shuffling_central_9":"自动机器翻译",
                "shuffling_central_10": "详细信息",
                "shuffling_central_11":"客户的软件应用程序需要翻译，但是没有对计算机编程文本进行归纳，所以提取文本和翻译文本显得非常不方便，我们为其量身制作了一套在应用程序代码内进行翻译修改的解决方案并提取字符串，解决了技术与非技术的问题。",
                "shuffling_central_12": "了解更多",
                "shuffling_central_13":"自动机器翻译",
                "shuffling_central_14": "详细信息",
                "shuffling_central_15":"安卓打包工具",
                "shuffling_central_16": "详细信息",
                "shuffling_central_17":"客户需要把产品上线全中国安卓渠道，其中大部分都是重复工作，我们为其量身定制打包工具，客户可以轻易的，批量的进行打包处理，根据客户的需求，加入其需要的模块，彻底满足此客户自身特有的解决方案。",
                "shuffling_central_18":"了解更多",
                "shuffling_central_19": "安卓打包工具",
                "shuffling_central_20":"详细信息",
                "shuffling_central_21":"批量后台管理",
                "shuffling_central_22": "详细信息",
                "shuffling_central_23":"客户有很多管理后台，要把管理后台的数据进行整理归纳，但是需要花费大量的人力物力去归纳总结，并反复计算才能得出结果，我们为其量身定制了一款后台管理程序，满足客户特有的数据计算方式和需求。",
                "shuffling_central_24": "了解更多",
                "shuffling_central_25":"批量后台管理",
                "shuffling_central_26": "详细信息",
                "shuffling_central_27":"批量制图工具",
                "shuffling_central_28": "详细信息",
                "shuffling_central_29":"客户的图片需要修改各种尺寸和图片大小进行调整，我们了分析客户的做图模式，量身定制了批量制图工具，节约人力成本，使其可以更专注美术灵感的思考。",
                "shuffling_central_30": "了解更多",
                "shuffling_central_31":"批量制图工具",
                "shuffling_central_32":"详细信息",
                "5_middle_modules_0":"何事之为",
                "5_middle_modules_1":"我们的主要服务",
                "5_middle_modules_2":" 软件工具设计",
                "5_middle_modules_3":"自动翻译、安卓反编译 ",
                "5_middle_modules_4":"网络数据抓取",
                "5_middle_modules_5":"APP上线监控 订制网络爬虫",
                "5_middle_modules_6":"提供解决方案",
                "5_middle_modules_7":"流程化设计 工具建议",
                "5_middle_modules_8":"自定义服务",
                "5_middle_modules_9":"A/B测试 模拟人工步骤",
                "5_middle_modules_10":"数据分析定制",
                "5_middle_modules_11":"可视化数据 数据挖掘",
                "5_middle_modules_12":"更多服务",
                "bottom_shuffling_0":"共享资源",
                "bottom_shuffling_1":"免费公共服务",
                "bottom_shuffling_2": "最近",
                "bottom_shuffling_3": "更新",
                "bottom_shuffling_4":"客户工具",
                "bottom_shuffling_5": "免费 | 公开",
                "bottom_shuffling_6":"感谢热心客户，客户公开的解决方案和软件工具",
                "bottom_shuffling_7": "更多",
                "bottom_shuffling_8":"最近",
                "bottom_shuffling_9":"更新",
                "bottom_shuffling_10": "推荐工具",
                "bottom_shuffling_11":"精选 | 高效",
                "bottom_shuffling_12": "感谢运营团队，高效率的第三方工具，让更多人了解提高工作效率的方法",
                "bottom_shuffling_13":"更多",
                "bottom_shuffling_14": "最近",
                "bottom_shuffling_15":"更新",
                "bottom_shuffling_16": "开源工具",
                "bottom_shuffling_17":"可用 | 良心",
                "bottom_shuffling_18":"感谢开发人员，针对开发人员推荐的优秀源代码 ",
                "bottom_shuffling_19": "更多",
                "bottom_shuffling_20":"最近",
                "bottom_shuffling_21": "更新",
                "bottom_shuffling_22":"收费工具",
                "bottom_shuffling_23": "专业 | 稳定",
                "bottom_shuffling_24":"感谢工程师，为了方便他人，自己所付出的辛苦劳动",
                "bottom_shuffling_25":"更多",
                "user_evaluation_0":"证明信",
                "user_evaluation_1":"来自客户的评价",
                "user_evaluation_2": "“我们从魔法棒智能学到了很多自动化的解决方案，以前不知道某些事情还能这样做，让我们感到非常惊讶，原来我们的工作效率可以更高，自从企业的成本也大大减少以后，我们都更专注于自己的专业度，更好的给社会服务”",
                "user_evaluation_3": "“太方便了，以后可以早点下班了”",
                "user_evaluation_4":"“问题得到了最直接的解决，没有出现和市面上一样，进入加钱改功能的死循环”",
                "user_evaluation_5": "“真棒！太好用了，有了这个工具后工作变得如此简单 ”",
                "user_evaluation_6":"东先生",
                "user_evaluation_7": "重庆",
                "user_evaluation_8":"王先生",
                "user_evaluation_9":"山东",
                "user_evaluation_10": "何女士",
                "user_evaluation_11":"上海",
                "user_evaluation_12": "李先生",
                "user_evaluation_13":"北京",
                "contact_0":"联系我们",
                "contact_1":"请根据下面的详细信息",
                "contact_2": "今天就联系我们!",
                "contact_3": "微信：18184079966",
                "contact_4":"邮箱：qin@MagicWandAI.com ",
                "contact_5": "工作时间：9:00am~17:00pm",
                "contact_6":"立即联系",
                "contact_7": "直接说明您的需求",
                "contact_8":"选择服务",
                "contact_9":"解决方案咨询",
                "contact_10": "软件工具定制",
                "contact_11":"网络数据获取",
                "contact_12": "新的合作需求",
                "contact_13":"其他意外惊喜",
                "registered_0":"立即注册成为会员",
                "registered_1":"您的所有信息将会保密不会用于任何事商业用途，所有信息均由服务器加密保存，",
                "registered_2": "会员信息是我们唯一联系您的方式。",
                "registered_3": "立即注册",
                "bottom_0":"魔法棒智能 为企业提供超过100个解决方案，客户需求，定制计划，过程研发，我们有非常完善的服务体系，最大化节省您的时间和成本，用最科学和最合理的方式给你一个满意的结果。",
                "bottom_1":"了解更多",
                "bottom_2": "用途链接",
                "bottom_3": "APP上线监控",
                "bottom_4":"自动机器翻译",
                "bottom_5":"安卓打包工具",
                "bottom_6":"批量后台管理",
                "bottom_7":"批量制图工具",
                "bottom_8":"关于公司",
                "bottom_9":"人工客服",
                "bottom_10":"证明信",
                "bottom_11":"问题帮助",
                "bottom_12": "联系我们",
                "bottom_13":"订阅我们",
                "bottom_14": "我们会定时为您推送我们的新项目和效率工具，发送邮箱地址即可订阅。",
                "bottom_15":"Copyright © 2010-2019 MagicWandAI.com 版权所有",
                "bottom_16": "帮助文档",
                "bottom_17":"隐私政策",
                "bottom_18":"服务条款"
            },

                                                                                      //en_cn
            {
                "title":"home",
                "top_0": "90 percent discount on consulting now",
                "top_1": "Consult now",
                "top_2": "Get help",
                "top_3": "Career Introduction",
                "top_4": "Feedback",
                "top_5": "Language selection",
                "top_6": "Chinese",
                "top_7": "English",
                "top_8": "Japanese",
                "top_9": "Korean",
                "banner_0": "Zhongqing Yubei District, Sino-Chongqing Love Metropolis",
                "banner_1": "China, Chongqing, Chongqing",
                "banner_2": "WeChat:",
                "banner_3": "18184079966",
                "banner_4": "Problem Help",
                "banner_5": "Home",
                "banner_6": "About the company",
                "banner_7": "Team Style",
                "banner_8": "Contact Us",
                "banner_9": "Home",
                "banner_10": "About the company",
                "banner_11": "Team Style",
                "banner_12": "About Us",
                "shuffling_0": "Magic Wand Intelligence helps you",
                "shuffling_1": "Save personal time and",
                "shuffling_2": "Reduce enterprise costs.",
                "shuffling_3": "Magic Wand Smart Business themes grow every day",
                "shuffling_4": "Thank you for believing us.",
                "shuffling_5": "Find out more about",
                "shuffling_6": "Magic Wand Intelligence ",
                "shuffling_7": " All-round protection of your data  and Your privacy ",
                "shuffling_8": " ",
                "shuffling_9": "Magic Wand Smart Business themes grow every day",
                "shuffling_10": "Thank you for believing us.",
                "shuffling_11": "Find out more about",
                "shuffling_12": "Professional for the Enterprise",
                "shuffling_13": "Provide intelligent software ",
                "shuffling_14": "and Automated programming services.",
                "shuffling_15": "Magic Wand Smart Business themes grow every day",
                "shuffling_16": "Thank you for believing us.",
                "shuffling_17": "Find out more about",
                "shuffling_18": "We are committed to providing individuals and businesses with automated software tool customization services, which is the direction of our business",
                "5_banner_0": "Analog computer operation",
                "5_banner_1": "Help complete the computer steps you need to complete, automatically, controllable, and efficiently accomplish the goals you need.",
                "5_banner_2": "Network data capture",
                "5_banner_3": "Obtain, organize and analyze network data to reduce human operation and time cost.",
                "5_banner_4": "Solution Development",
                "5_banner_5": "Provide the right solution for individual and business-specific situations.",
                "5_banner_6": "Data Orientation Analysis",
                "5_banner_7": "Visualize and analyze mining of existing data.",
                "5_banner_8": "Automation Software Design",
                "5_banner_9": "Customize the automation programs they need for individuals or businesses",
                "about_0": "About Us",
                "about_1": "Thanks for trusting magic Wand Intelligence",
                "about_2": "Our goal is simple, to give users the simplest and most direct solution",
                "about_3": "We need to make users feel that software customization and automated programming are not so complex, and the most important purpose is to get users the solution in the simplest way to let them know what we are doing and what we are going to do.",
                "about_4": "We present to our customers in the most concise and transparent way, everyone can easily enter the era of automation, so that time becomes more valuable, so that individuals and enterprises focus on thinking more needs to pay attention to things, hope that through efficient and highly automated processes and services, for social development to do their modest efforts.",
                "about_5": "Shan",
                "about_6": "Efficient",
                "about_7": "Face the problem",
                "about_8": "Professional",
                "about_9": "Troubleshoot problems",
                "about_10": "Transparent",
                "about_11": "Process tracking",
                "shuffling_central_0": "What's the difference?",
                "shuffling_central_1": "Our most recent project",
                "shuffling_central_2": "More services",
                "shuffling_central_3": "APP on-line monitoring",
                "shuffling_central_4": "More info",
                "shuffling_central_5": "Customers want to know if their apps are online and have similar apps, and we've tailored a big data acquisition solution that gives users access to the data they want",
                "shuffling_central_6": "Find out more about",
                "shuffling_central_7": "APP on-line monitoring",
                "shuffling_central_8": "More info",
                "shuffling_central_9": "Automatic machine translation",
                "shuffling_central_10": "More info",
                "shuffling_central_11": "The customer's software application needs to be translated, but the computer programming text is not summed up, so the extraction of text and translation text is very inconvenient, we have tailored a set of application code for translation and modification of the solution and extract strings, to solve technical and non-technical problems.",
                "shuffling_central_12": "Find out more about",
                "shuffling_central_13": "Automatic machine translation",
                "shuffling_central_14": "More info",
                "shuffling_central_15": "Android Packaging Tools",
                "shuffling_central_16": "More info",
                "shuffling_central_17": "Customers need to put products online across the security and Android channels, most of which are repetitive work, we tailor-made packaging tools for it, customers can easily, bulk packaging processing, according to customer needs, add their needs of the module, thoroughly meet the customer's own unique solution.",
                "shuffling_central_18": "Find out more about",
                "shuffling_central_19": "Android Packaging Tools",
                "shuffling_central_20": "More info",
                "shuffling_central_21": "Bulk Background Management",
                "shuffling_central_22": "More info",
                "shuffling_central_23": "Customers have a lot of management background, to manage the background of the data collation, but it takes a lot of human and material resources to summarize, and repeatedly calculate to produce results, we have tailored a background management program to meet customer-specific data calculation methods and needs.",
                "shuffling_central_24": "Find out more about",
                "shuffling_central_25": "Bulk Background Management",
                "shuffling_central_26": "More info",
                "shuffling_central_27": "Bulk Mapping Tools",
                "shuffling_central_28": "More info",
                "shuffling_central_29": "Customer pictures need to modify a variety of sizes and picture size to adjust, we analyzed the customer's mapping mode, tailor-made batch mapping tools, saving labor costs, so that it can more focus on art inspiration thinking.",
                "shuffling_central_30": "Find out more about",
                "shuffling_central_31": "Bulk Mapping Tools",
                "shuffling_central_32": "More info",
                "5_middle_modules_0": "What is it?",
                "5_middle_modules_1": "Our main services",
                "5_middle_modules_2": "Software tool design",
                "5_middle_modules_3": "Automatic translation, Android reverse compilation ",
                "5_middle_modules_4": "Network data crawl",
                "5_middle_modules_5": "APP on-line monitoring customized web crawler",
                "5_middle_modules_6": "Provide solutions",
                "5_middle_modules_7": "Workflow Design Tool Recommendations",
                "5_middle_modules_8": "Custom Services",
                "5_middle_modules_9": "A/B test simulates manual steps",
                "5_middle_modules_10": "Data Analysis Customization",
                "5_middle_modules_11": "Visualization of data Data mining",
                "5_middle_modules_12": "More services",
                "bottom_shuffling_0": "Shared resources",
                "bottom_shuffling_1": "Free public Service",
                "bottom_shuffling_2": "Recent",
                "bottom_shuffling_3": "Update",
                "bottom_shuffling_4": "Customer Tools",
                "bottom_shuffling_5": "Free | Public",
                "bottom_shuffling_6": "Thanks to enthusiastic customers, customers open solutions and software tools",
                "bottom_shuffling_7": "More",
                "bottom_shuffling_8": "Recent",
                "bottom_shuffling_9": "Update",
                "bottom_shuffling_10": "Featured Tools",
                "bottom_shuffling_11": "Featured | Efficient",
                "bottom_shuffling_12": "Thanks to the operations team, the efficient third-party tools, to make more people aware of ways to improve productivity",
                "bottom_shuffling_13": "More",
                "bottom_shuffling_14": "Recent",
                "bottom_shuffling_15": "Update",
                "bottom_shuffling_16": "Open Source Tools",
                "bottom_shuffling_17": "Available | Conscience",
                "bottom_shuffling_18": "Thanks to developers, the best source code recommended for Developers ",
                "bottom_shuffling_19": "More",
                "bottom_shuffling_20": "Recent",
                "bottom_shuffling_21": "Update",
                "bottom_shuffling_22": "Charging tools",
                "bottom_shuffling_23": "Professional | Stability",
                "bottom_shuffling_24": "Thanks to the engineers, for the convenience of others, their own hard work",
                "bottom_shuffling_25": "More",
                "user_evaluation_0": "Letter",
                "user_evaluation_1": "Reviews from Customers",
                "user_evaluation_2": "We learned from magic wand intelligence to a lot of automated solutions, previously did not know that certain things can do this, let us be very surprised, the original we can be more efficient, since the cost of the enterprise has been greatly reduced, we are more focused on their own professionalism, better service to the community",
                "user_evaluation_3": "It's so convenient, you can get off work early.",
                "user_evaluation_4": "The problem has been the most direct solution, did not appear as on the market, into the addition of money to change the function of the dead cycle",
                "user_evaluation_5": "Awesome place to be! It's so easy to use, it's so easy to work when you have this tool. ",
                "user_evaluation_6": "Mr. Dong",
                "user_evaluation_7": "Chongqing",
                "user_evaluation_8": "Mr. Wang",
                "user_evaluation_9": "Shandong",
                "user_evaluation_10": "Ms. Ho",
                "user_evaluation_11": "Shanghai",
                "user_evaluation_12": "Mr. Li",
                "user_evaluation_13": "Beijing",
                "contact_0": "Contact Us",
                "contact_1": "Please click on the details below",
                "contact_2": "Contact us today!",
                "contact_3": "WeChat: 18184079966",
                "contact_4": "Email: qin@MagicWandAI.com ",
                "contact_5": "Working hours: 9:00am~17:00pm",
                "contact_6": "Contact now",
                "contact_7": "Direct description of your needs",
                "contact_8": "Select a service",
                "contact_9": "Solution Consulting",
                "contact_10": "Software tool Customization",
                "contact_11": "Network data acquisition",
                "contact_12": "New requirements for cooperation",
                "contact_13": "Other unexpected surprises",
                "registered_0": "Register as a member now",
                "registered_1": "All of your information will be kept confidential and will not be used for any commercial purpose. All information is stored encrypted by the server.",
                "registered_2": "Membership information is the only way we contact you.",
                "registered_3": "Register Now",
                "bottom_0": "Magic Wand Intelligence for enterprises to provide more than 100 solutions, customer needs, customized plans, process research and development, we have a very perfect service system, to maximize the savings of your time and cost, in the most scientific and reasonable way to give you a satisfactory result.",
                "bottom_1": "Find out more about",
                "bottom_2": "Purpose links",
                "bottom_3": "APP on-line monitoring",
                "bottom_4": "Auto machine translation",
                "bottom_5": "Android Packaging Tools",
                "bottom_6": "Bulk  Management",
                "bottom_7": "Bulk Mapping Tools",
                "bottom_8": "About the company",
                "bottom_9": "Manual Customer Service",
                "bottom_10": "Letter",
                "bottom_11": "Problem Help",
                "bottom_12": "Contact Us",
                "bottom_13": "Subscribe to our",
                "bottom_14": "We will regularly push our new projects and efficiency tools for you, sending email addresses to subscribe.",
                "bottom_15": "Copyright © 2010-2019 MagicWandAI.com all rights reserved",
                "bottom_16": "Help documentation",
                "bottom_17": "Privacy Policy",
                "bottom_18": "Terms of Service"
            },
                                                                                    //日语
            {
                "top_0":"今すぐコンサルティングの 90% 割引",
                "top_1":"今相談する",
                "top_2":"助けを得る",
                "top_3":"キャリア紹介",
                "top_4":"フィードバック",
                "top_5":"言語選択",
                "top_6":"中国語",
                "top_7":"英語",
                "top_8": "日本語",
                "top_9": "ハングル",
                "banner_0":"重慶ラブシティ、重北、ube北区",
                "banner_1":"中国、重慶、重慶",
                "banner_2":"wechat：",
                "banner_3":"18184079966",
                "banner_4":"問題のヘルプ",
                "banner_5":"ホーム",
                "banner_6":"会社について",
                "banner_7":"チームスタイル",
                "banner_8":"お問い合わせ",
                "banner_9":"ホーム",
                "banner_10":"会社概要",
                "banner_11":"チームスタイル",
                "banner_12":"私達について",
                "shuffling_0":"魔法の杖の知性はあなたを助ける",
                "shuffling_1":"個人的な時間を節約して",
                "shuffling_2":"事業コストを削減します。",
                "shuffling_3":"魔法の杖スマートビジネステーマは毎日成長します",
                "shuffling_4":"私たちを信頼してくれてありがとう。",
                "shuffling_5":"もっと詳しく",
                "shuffling_6":"魔法の杖の知性",
                "shuffling_7":"データとあらゆる側面を保護する",
                "shuffling_8":"あなたのプライバシー",
                "shuffling_9":"魔法の杖スマートビジネステーマは毎日成長します",
                "shuffling_10":"私たちを信頼してくれてありがとう。",
                "shuffling_11":"もっと詳しく",
                "shuffling_12":"企業のための専門家",
                "shuffling_13":"インテリジェントなソフトウェアを提供する",
                "shuffling_14":"自動プログラミングサービス",
                "shuffling_15":"魔法の杖スマートビジネステーマは毎日成長します",
                "shuffling_16":"私たちを信頼してくれてありがとう",
                "shuffling_17":"もっと詳しく",
                "shuffling_18":"私たちは、ビジネスの方向性である自動化されたソフトウェアツールのカスタマイズサービスを個人や企業に提供することにコミットしています",
                "5_banner_0":"アナログコンピュータ操作",
                "5_banner_1":"必要な目標を達成するために必要なコンピュータ手順を、自動的に、制御可能かつ効率的に達成するのに役立ちます。",
                "5_banner_2":" ネットワークデータのクロール",
                "5_banner_3":"ネットワークデータを取得、整理、および分析して、人件費と時間のコストを削減します。",
                "5_banner_4":"ソリューション開発",
                "5_banner_5":"個々の状況やビジネス特有のシチュエーションに適したソリューションを提供します。",
                "5_banner_6":"データ指向分析",
                "5_banner_7":"既存のデータを視覚化して分析します。",
                "5_banner_8":"オートメーションソフトウェアの設計",
                "5_banner_9":"個人または企業に必要な自動化プログラムをカスタマイズする",
                "about_0":"私達について",
                "about_1":"魔法の杖の知性を信頼してくれてありがとう",
                "about_2":"私たちの目標はシンプルで、ユーザーに最も簡単で直接的な解決策を提供することです。",
                "about_3":"ソフトウェアのカスタマイズや自動プログラミングはそれほど複雑ではないとユーザーに感じさせる必要があります。最も重要な目的は、ユーザーに最も簡単な方法でソリューションを入手させ、自分のしていること、やりたいことを理解させることです。",
                "about_4":"私たちは、最も簡潔で透過的な方法でお客様に提示します, 誰もが簡単に自動化の時代に入ることができます, 時間がより価値があるように, 個人や企業が物事に注意を払うためにより多くのニーズを考えることに焦点を当てるように, 効率的かつ高度に自動化されたプロセスやサービスを",
                "about_5":"おー",
                "about_6":"効率的",
                "about_7":"問題に直面する",
                "about_8":"プロ",
                "about_9":"問題解決",
                "about_10":"透明",
                "about_11":"プロセス追跡",
                "shuffling_central_0":"問題は何ですか？",
                "shuffling_central_1":"最新のプロジェクト",
                "shuffling_central_2":"より多くのサービス",
                "shuffling_central_3":"APPオンライン監視",
                "shuffling_central_4":"詳細情報",
                "shuffling_central_5":"顧客はアプリの世界的な存在感と同様のアプリを知りたい、私たちはユーザーが欲しいデータを取得できるようにビッグデータ取得ソリューションを調整しました。",
                "shuffling_central_6":"もっと詳しく",
                "shuffling_central_7":"アプリのオンライン監視",
                "shuffling_central_8":"詳細",
                "shuffling_central_9":"自動機械翻訳",
                "shuffling_central_10":"詳細情報",
                "shuffling_central_11":"クライアントのソフトウェアアプリケーションは翻訳する必要がありますが、コンピュータプログラミングのテキストは要約されていないため、テキストを抽出してテキストを翻訳するのは非常に不便です。",
                "shuffling_central_12":"もっと詳しく",
                "shuffling_central_13":"自動機械翻訳",
                "shuffling_central_14":"詳細",
                "shuffling_central_15":"Androidのパッケージングツール",
                "shuffling_central_16":"詳細情報",
                "shuffling_central_17":"顧客は自分の製品を中国のAndroidチャネルでオンラインにする必要がありますが、そのほとんどが繰り返し作業で、私たちはそれらのためにパッケージングツールを調整し、顧客はそれらをバッチで簡単にパッケージし、必要に応じて必要なモジュールを追加できます。",
                "shuffling_central_18":"もっと詳しく",
                "shuffling_central_19":"アンドロイドパッケージングツール",
                "shuffling_central_20":"詳細",
                "shuffling_central_21":"バッチバックグラウンド管理",
                "shuffling_central_22":"詳細情報",
                "shuffling_central_23":"得意先には多くの経営バックグラウンドがあり、その管理バックグラウンドのデータはソートおよび要約する必要がありますが、要約および要約には多くの人的資源および資材リソースが必要であり、結果を繰り返し計算することができます。",
                "shuffling_central_24":"もっと詳しく",
                "shuffling_central_25":"一括バックグラウンド管理",
                "shuffling_central_26":"詳細",
                "shuffling_central_27":"バッチチャート作成ツール",
                "shuffling_central_28":"詳細情報",
                "shuffling_central_29":"顧客の絵は様々なサイズや画像サイズで修正する必要があります私たちは顧客の描画モードを分析し、バッチ描画ツールを調整し、人件費を節約し、それを芸術のインスピレーションにもっと焦点を合わせました。",
                "shuffling_central_30":"もっと詳しく",
                "shuffling_central_31":"バルクマッピングツール",
                "shuffling_central_32":"詳細",
                "5_middle_modules_0":"それは何ですか？",
                "5_middle_modules_1":"主なサービス",
                "5_middle_modules_2":"ソフトウェアツール設計",
                "5_middle_modules_3":"自動翻訳、Androidの逆コンパイル",
                "5_middle_modules_4":"ネットワークデータのクロール",
                "5_middle_modules_5":"APPオンライン監視カスタムWebクローラー",
                "5_middle_modules_6":"解決策を提供する",
                "5_middle_modules_7":"ワークフロー設計ツールの推奨事項",
                "5_middle_modules_8":"カスタムサービス",
                "5_middle_modules_9":"A / Bテストシミュレーションの手動手順",
                "5_middle_modules_10":"データ分析のカスタマイズ",
                "5_middle_modules_11":"ビジュアルデータマイニング",
                "5_middle_modules_12":"より多くのサービス",
                "bottom_shuffling_0":"共有リソース",
                "bottom_shuffling_1":"無料の公共サービス",
                "bottom_shuffling_2":"最近",
                "bottom_shuffling_3":"更新",
                "bottom_shuffling_4":"顧客ツール",
                "bottom_shuffling_5":"無料|公開",
                "bottom_shuffling_6":"熱心なお客様のおかげで、お客様はソリューションとソフトウェアツールをオープン",
                "bottom_shuffling_7":"もっと",
                "bottom_shuffling_8":"最近",
                "bottom_shuffling_9":"更新",
                "bottom_shuffling_10":"おすすめツール",
                "bottom_shuffling_11":"注目の|効率的な",
                "bottom_shuffling_12":"運用チーム、効率的なサードパーティ製ツールのおかげで、生産性を向上させる方法をより多くの人に知らせることができる",
                "bottom_shuffling_13":"もっと",
                "bottom_shuffling_14":"最近",
                "bottom_shuffling_15":"更新",
                "bottom_shuffling_16":"オープンソースツール",
                "bottom_shuffling_17":"利用可能|良心",
                "bottom_shuffling_18":"開発者のおかげで、開発者に推奨される最高のソースコード ",
                "bottom_shuffling_19":"もっと",
                "bottom_shuffling_20":"最近",
                "bottom_shuffling_21":"更新",
                "bottom_shuffling_22":"トリングツール",
                "bottom_shuffling_23":"プロ|安定した",
                "bottom_shuffling_24":"エンジニアのおかげで、他人の便宜のために、自分のハードワーク",
                "bottom_shuffling_25":"もっと",
                "user_evaluation_0":"証明書",
                "user_evaluation_1":"お客様からのレビュー",
                "user_evaluation_2":"私たちはMagic Stick Intelligenceから多くの自動化された解決策を学びました。まだ何もできることを私たちは知りませんでした。私たちは非常に驚きました。より効率的に仕事をすることができます。",
                "user_evaluation_3":"それはあまりにも便利です、あなたはすぐに仕事から降りることができます。",
                "user_evaluation_4":"問題は、最も直接的な解決策となっている、市場では、デッドサイクルの機能を変更するためにお金の追加に表示されませんでした",
                "user_evaluation_5":"すごい！使うのはとてもいいです、このツールを使うのはとても簡単です",
                "user_evaluation_6":"ドン氏",
                "user_evaluation_7":"重 慶",
                "user_evaluation_8":"王さん",
                "user_evaluation_9":"山東省",
                "user_evaluation_10":"ホーさん",
                "user_evaluation_11":"上海",
                "user_evaluation_12":"李さん",
                "user_evaluation_13":"北京",
                "contact_0":"お問い合わせ",
                "contact_1":"以下の詳細に従ってください",
                "contact_2":"今すぐお問い合わせください!",
                "contact_3":"wechat：18184079966",
                "contact_4":"電子メール：qin@MagicWandAI.com",
                "contact_5":"営業時間: 9: 00am ~ 17: 00pm",
                "contact_6":"今連絡する",
                "contact_7":"あなたのニーズを直接説明する",
                "contact_8":"サービスの選択",
                "contact_9":"ソリューションコンサルティング",
                "contact_10":"ソフトウェアツールのカスタマイズ",
                "contact_11":"ネットワークデータの取得",
                "contact_12":"新たな協力ニーズ",
                "contact_13":"その他の驚き",
                "registered_0":"今すぐ会員登録",
                "registered_1":"あなたのすべての情報は機密に保たれ、いかなる商業目的にも使用されません。すべての情報はサーバーによって暗号化されます。",
                "registered_2":"私達があなたに連絡することができる唯一の方法は会員情報です。",
                "registered_3":"今すぐ登録",
                "bottom_0":"マジックスティックスマートは100以上のソリューション、顧客のニーズ、カスタマイズされた計画、プロセス開発を企業に提供します、我々はあなたの最も科学的で合理的な方法であなたに満足を与えます。",
                "bottom_1":"もっと詳しく",
                "bottom_2":"目的リンク",
                "bottom_3":"APPオンライン監視",
                "bottom_4":"自動機械翻訳",
                "bottom_5":"アンドロイドパッケージングツール",
                "bottom_6":"バッチバックグラウンド管理",
                "bottom_7":"バッチチャート作成ツール",
                "bottom_8":"会社概要",
                "bottom_9":"手動カスタマーサービス",
                "bottom_10":"証明書",
                "bottom_11":"問題のヘルプ",
                "bottom_12":"お問い合わせ",
                "bottom_13":"私たちを購読する",
                "bottom_14":"私たちは定期的にあなたのための新しいプロジェクトと効率ツールをプッシュします, 購読する電子メールアドレスを送信.",
                "bottom_15":"著作権©2010-2019 MagicWandAI.comすべての権利予約",
                "bottom_16":"ヘルプ文書",
                "bottom_17":"プライバシーポリシー",
                "bottom_18":"利用規約"
            },

                                                                                    //韩语
            {
                "top_0":"90% 할인에 대 한 컨설팅 지금",
                "top_1":"지금 문의",
                "top_2":"도움 받기",
                "top_3":"커리어 소개",
                "top_4":"피드백",
                "top_5":"언어 선택",
                "top_6":"중국어",
                "top_7":"영어",
                "top_8": "일본어",
                "top_9": "한국어",
                "banner_0":"중경 러브 시티 (Zhongyu Love City), 충칭 유북 구",
                "banner_1":"중국, 충칭, 충칭",
                "banner_2":"미크롱 편지 :",
                "banner_3":"18184079966",
                "banner_4":"문제 도움말",
                "banner_5":"홈",
                "banner_6":"회사 소개",
                "banner_7":"팀 스타일",
                "banner_8":"문의하기",
                "banner_9":"홈",
                "banner_10":"회사 소개",
                "banner_11":"팀 스타일",
                "banner_12":"회사 소개",
                "shuffling_0":"마술 지팡이 지능을 사용 하면",
                "shuffling_1":"개인적인 시간을 절약하고",
                "shuffling_2":"비즈니스 비용 절감.",
                "shuffling_3":"마술 지팡이 스마트 비즈니스 테마는 매일 성장",
                "shuffling_4":"우리를 신뢰 해 주셔서 감사합니다.",
                "shuffling_5":"더 알아보기",
                "shuffling_6":"마술 지팡이 지능",
                "shuffling_7":"데이터 및 모든 측면 보호",
                "shuffling_8":"당신의 프라이버시.",
                "shuffling_9":"마술 지팡이 스마트 비즈니스 테마는 매일 성장",
                "shuffling_10":"우리를 신뢰 해 주셔서 감사합니다.",
                "shuffling_11":"더 알아보기",
                "shuffling_12":"기업을 위한 전문가",
                "shuffling_13":"지능형 소프트웨어 및",
                "shuffling_14":"자동화 된 프로그래밍 서비스.",
                "shuffling_15":"마술 지팡이 스마트 비즈니스 테마는 매일 성장",
                "shuffling_16":"우리를 신뢰 해 주셔서 감사합니다.",
                "shuffling_17":"더 알아보기",
                "shuffling_18":"당사는 비즈니스의 방향성 인 자동화 된 소프트웨어 툴 맞춤화 서비스를 개인 및 기업에 제공 하기 위해 최선을 다하고 있습니다.",
                "5_banner_0":"아날로그 컴퓨터 작동",
                "5_banner_1":"완료해야하는 컴퓨터 단계를 완료하고 필요한 목표를 자동으로 제어 가능하고 효율적으로 완료하도록 도와줍니다.",
                "5_banner_2":" 네트워크 데이터 크롤링",
                "5_banner_3":"네트워크 데이터를 수집, 구성 및 분석하여 인건비 및 시간 비용을 절감하십시오.",
                "5_banner_4":"솔루션 개발",
                "5_banner_5":"개별 및 비즈니스 관련 상황에 적합 한 솔루션을 제공 합니다.",
                "5_banner_6":"데이터 방향 분석",
                "5_banner_7":"기존 데이터를 시각화하고 분석합니다.",
                "5_banner_8":"자동화 소프트웨어 설계",
                "5_banner_9":"개인 또는 기업에 필요한 자동화 프로그램을 사용자 정의하십시오.",
                "about_0":"회사 소개",
                "about_1":"마법의 지팡이 지능을 신뢰 주셔서 감사 합니다",
                "about_2":"우리의 목표는 간단하며 사용자에게 가장 단순하고 가장 직접적인 솔루션을 제공합니다.",
                "about_3":"우리는 사용자가 소프트웨어 사용자 정의 및 자동화 된 프로그래밍이 복잡하지 않다는 느낌을 갖도록해야합니다. 가장 중요한 목적은 사용자가 가장 단순한 방법으로 솔루션을 얻도록하고 사용자가 수행중인 작업, 수행하고자하는 작업을 이해하도록하는 것입니다.",
                "about_4":"우리는 가장 간결 하 고 투명 한 방법으로 고객에 게 제시, 모든 사람이 쉽게 자동화의 시대를 입력 할 수 있습니다, 시간이 더 가치 있게, 그래서 개인과 기업이 사물에 관심을 지불 하는 더 많은 필요를 생각에 초점을 맞추고, 사회 발전을 통해 그 겸손 한 노력을 할 수 있는 효율적이 고 고도로 자동화 된 프로세스와 서비스를 통해, 희망.",
                "about_5":"覃 于 ンプ",
                "about_6":"효율적",
                "about_7":"문제에 직면",
                "about_8":"전문가",
                "about_9":"문제 해결",
                "about_10":"투명",
                "about_11":"프로세스 추적",
                "shuffling_central_0":"무슨 일인데?",
                "shuffling_central_1":"우리의 가장 최근의 프로젝트",
                "shuffling_central_2":"더 많은 서비스",
                "shuffling_central_3":"APP 온라인 모니터링",
                "shuffling_central_4":"더 많은 정보",
                "shuffling_central_5":"고객은 앱의 세계적인 인지도 및 이와 유사한 앱을 알고 싶어 사용자가 원하는 데이터를 얻을 수있는 대용량 데이터 수집 솔루션을 개발했습니다.",
                "shuffling_central_6":"더 알아보기",
                "shuffling_central_7":"앱 온라인 모니터링",
                "shuffling_central_8":"세부 정보",
                "shuffling_central_9":"자동 기계 번역",
                "shuffling_central_10":"더 많은 정보",
                "shuffling_central_11":"클라이언트의 소프트웨어 응용 프로그램은 번역해야하지만 컴퓨터 프로그래밍 텍스트는 요약되어 있지 않으므로 텍스트를 추출하고 텍스트를 번역하는 것은 매우 불편합니다. 우리는 응용 프로그램 코드에서 번역 수정을위한 솔루션을 작성하고 추출했습니다. ",
                "shuffling_central_12":"더 알아보기",
                "shuffling_central_13":"자동 기계 번역",
                "shuffling_central_14":"세부 정보",
                "shuffling_central_15":"안드로이드 포장 도구",
                "shuffling_central_16":"더 많은 정보",
                "shuffling_central_17":"고객은 중국 안드로이드 채널에 제품을 온라인으로 배치해야하며 그 대부분은 반복적 인 작업입니다. 우리는 패키지 도구를 맞춤형으로 묶어 고객이 필요로하는 모듈을 쉽게 추가 할 수 있습니다. ",
                "shuffling_central_18":"더 알아보기",
                "shuffling_central_19":"안 드 로이드 패키징 도구",
                "shuffling_central_20":"세부 정보",
                "shuffling_central_21":"일괄 백그라운드 관리",
                "shuffling_central_22":"더 많은 정보",
                "shuffling_central_23":"고객은 많은 관리 배경을 가지고 있으며 관리 배경의 데이터는 정렬 및 요약되어야하지만 요약 및 요약하기 위해 많은 인력 및 물적 자원이 필요하며 결과를 반복적으로 계산할 수 있습니다. 고객 만족을위한 백그라운드 관리 프로그램을 사용자 정의했습니다. ",
                "shuffling_central_24":"더 알아보기",
                "shuffling_central_25":"대량 백그라운드 관리",
                "shuffling_central_26":"세부 정보",
                "shuffling_central_27":"배치 차트 작성 도구",
                "shuffling_central_28":"더 많은 정보",
                "shuffling_central_29":"고객의 그림을 다양한 크기와 이미지 크기로 수정해야하며, 고객의 드로잉 모드를 분석하고 일괄 드로잉 도구를 맞춤화하고 인건비를 절감하며 예술의 영감에 더 집중하게했습니다.",
                "shuffling_central_30":"더 알아보기",
                "shuffling_central_31":"벌크 매핑 도구",
                "shuffling_central_32":"세부 정보",
                "5_middle_modules_0":"이게 뭐야?",
                "5_middle_modules_1":"우리의 주요 서비스",
                "5_middle_modules_2":"소프트웨어 도구 설계",
                "5_middle_modules_3":"자동 번역, Android 디 컴파일",
                "5_middle_modules_4":"네트워크 데이터 크롤링",
                "5_middle_modules_5":"APP 온라인 모니터링 맞춤 웹 크롤러",
                "5_middle_modules_6":"솔루션 제공",
                "5_middle_modules_7":"워크플로 디자인 도구 권장 사항",
                "5_middle_modules_8":"맞춤 서비스",
                "5_middle_modules_9":"A / B 테스트 시뮬레이션 수동 단계",
                "5_middle_modules_10":"데이터 분석 사용자 정의",
                "5_middle_modules_11":"비주얼 데이터 마이닝",
                "5_middle_modules_12":"더 많은 서비스",
                "bottom_shuffling_0":"공유 리소스",
                "bottom_shuffling_1":"무료 공공 서비스",
                "bottom_shuffling_2":"최근에",
                "bottom_shuffling_3":"업데이트",
                "bottom_shuffling_4":"고객 도구",
                "bottom_shuffling_5":"무료 | 공개",
                "bottom_shuffling_6":"열정적 인 고객 덕분에 고객은 솔루션 및 소프트웨어 도구를 열 수 있습니다.",
                "bottom_shuffling_7":"기타",
                "bottom_shuffling_8":"최근에",
                "bottom_shuffling_9":"업데이트",
                "bottom_shuffling_10":"추천 도구",
                "bottom_shuffling_11":"특집 | 능률적 인",
                "bottom_shuffling_12":"운영 팀, 효율적인 제 3 자 도구 덕분에 더 많은 사람들이 생산성을 향상 시킬 수 있는 방법을 인식 하 게 합니다.",
                "bottom_shuffling_13":"기타",
                "bottom_shuffling_14":"최근에",
                "bottom_shuffling_15":"업데이트",
                "bottom_shuffling_16":"오픈 소스 도구",
                "bottom_shuffling_17":"가능 | 양심",
                "bottom_shuffling_18":"개발자 들 덕분에, 개발자 들에 게 권장 되는 최고의 소스 코드 ",
                "bottom_shuffling_19":"기타",
                "bottom_shuffling_20":"최근에",
                "bottom_shuffling_21":"업데이트",
                "bottom_shuffling_22":"툴링 도구",
                "bottom_shuffling_23":"전문가 | 안정적",
                "bottom_shuffling_24":"엔지니어 덕분에, 다른 사람의 편의를 위해, 그들의 자신의 노력",
                "bottom_shuffling_25":"기타",
                "user_evaluation_0":"증명서",
                "user_evaluation_1":"고객의 리뷰",
                "user_evaluation_2":"우리는 Magic Stick Intelligence에서 많은 자동화 솔루션을 배웠고 이전에 할 수있는 일이 있는지 몰랐지만 놀랍게도 효율적으로 일할 수있었습니다. 회사 비용이 크게 감소했기 때문에 ",
                "user_evaluation_3":"너무 편리하다. 곧 일할 수있다.",
                "user_evaluation_4":"문제는 죽은 주기의 기능을 변경 하는 돈의 추가로, 시장에 표시 되지 않았다, 가장 직접적인 해결책이 되었습니다",
                "user_evaluation_5":"멋지다! 사용하는 것이 너무 좋으며이 도구로 작업하기가 쉽다",
                "user_evaluation_6":"동씨",
                "user_evaluation_7":"충칭",
                "user_evaluation_8":"왕씨",
                "user_evaluation_9":"산동",
                "user_evaluation_10":"호",
                "user_evaluation_11":"상하이",
                "user_evaluation_12":"리 씨",
                "user_evaluation_13":"베이징",
                "contact_0":"문의하기",
                "contact_1":"아래의 세부 정보를 따르십시오.",
                "contact_2":"오늘 저희에 게 연락 하십시오!",
                "contact_3":"미크롱 편지: 18184079966",
                "contact_4":"이메일 : qin@MagicWandAI.com",
                "contact_5":"근무 시간: 9:00am ~ 17 시",
                "contact_6":"기업에게 연락 해주기",
                "contact_7":"필요 사항을 직접 설명하십시오.",
                "contact_8":"서비스를 선택",
                "contact_9":"솔루션 컨설팅",
                "contact_10":"소프트웨어 도구 사용자 정의",
                "contact_11":"네트워크 데이터 수집",
                "contact_12":"새로운 협력 요구",
                "contact_13":"기타 놀라움",
                "registered_0":"지금 회원으로 등록 하기",
                "registered_1":"모든 정보는 기밀로 유지되며 상업적 목적으로 사용되지 않으며 모든 정보는 서버에 의해 암호화됩니다.",
                "registered_2":"회원 정보는 우리가 연락 할 수있는 유일한 방법입니다.",
                "registered_3":"지금 등록 하기",
                "bottom_0":"Magic Stick Smart는 100 가지가 넘는 솔루션, 고객 요구, 맞춤형 계획, 프로세스 개발을 제공하며, 시간과 비용을 최대화하여 매우 과학적이고 합리적인 방식으로 고객 만족을 제공합니다. ",
                "bottom_1":"더 알아보기",
                "bottom_2":"목적 링크",
                "bottom_3":"APP 온라인 모니터링",
                "bottom_4":"자동 기계 번역",
                "bottom_5":"안 드 로이드 패키징 도구",
                "bottom_6":"일괄 백그라운드 관리",
                "bottom_7":"배치 차트 작성 도구",
                "bottom_8":"회사 소개",
                "bottom_9":"수동 고객 서비스",
                "bottom_10":"증명서",
                "bottom_11":"문제 도움말",
                "bottom_12":"문의하기",
                "bottom_13":"우리에게 구독",
                "bottom_14":"우리는 정기적으로 새로운 프로젝트와 효율성 도구를 밀어 구독 할 이메일 주소를 보냅니다.",
                "bottom_15":"저작권 © 2010-2019 MagicWandAI.com 모든 권리 보유",
                "bottom_16":"도움말 문서",
                "bottom_17":"개인 정보 보호 정책",
                "bottom_18":"서비스 약관"
            },
        /////////////////////////////////////////团队风采翻译///////////////////////////////////////////////////////////////////
                                                                                    // 中文
            {
                "title":"团队风采",
                "top_0": "现在咨询享受9折优惠",
                "top_1":"立即咨询",
                "top_2":"获取帮助",
                "top_3": "职业介绍",
                "top_4":"信息反馈",
                "top_5": "语言选择",
                "top_6":"中文",
                "top_7": "English",
                "top_8": "日语",
                "top_9": "韩语",
                "banner_0":"重庆市渝北区中渝爱都会",
                "banner_1":"中国，重庆，重庆市",
                "banner_2":"微信：",
                "banner_3":"18184079966",
                "banner_4":"问题帮助",
                "banner_5":"首页",
                "banner_6":"关于公司",
                "banner_7":"团队风采",
                "banner_8":"联系我们",
                "banner_9":"首页",
                "banner_10":"关于公司",
                "banner_11":"团队风采",
                "banner_12":"关于我们",
                "banner_13":"团队风采",
                "banner_14":"首页",
                "banner_15":"关于我们",
                "banner_16":"联系我们团队",
                "banner_17":"分享",
                "display_module_0":"覃于澎 ",
                "display_module_1":"设计架构",
                "display_module_2":"针对需求和技术可行性",
                "display_module_3":"设计出最优的程序设计思路。",
                "display_module_4":"曲永杰",
                "display_module_5":"客户端设计师",
                "display_module_6":"把最为直观的一面设计给客户",
                "display_module_7":"用最简明的方式解决您的需求。",
                "display_module_8":"李东海",
                "display_module_9":"自动化设计师",
                "display_module_10":"分析所有的步骤并把它们简化成一步",
                "display_module_11":"设计自动化流程是我的职责。",
                "display_module_12":"谭昊",
                "display_module_13":"加密研究员",
                "display_module_14":"保证数据的安全和隐私",
                "display_module_15":"默默为用户防范每一次安全隐患。",
                "display_module_16":"侯尧",
                "display_module_17":"数据分析师",
                "display_module_18":"获取数据分析数据设计算法",
                "display_module_19":"使用算法，稳定，高效，智能。",
                "display_module_20":"李雅清",
                "display_module_21":"项目经理",
                "display_module_22":"技术人员和非技术人员的桥梁",
                "display_module_23":"把疑问给我，把解决方案给你",
                "display_module_24":"斯素婷",
                "display_module_25":"客户经理",
                "display_module_26":"跟进内外项目进度，了解客户需求 ",
                "display_module_27":"所有的客户问题都做到有问必答。 ",
                "display_module_28":"张元琦",
                "display_module_29":"软件设计师",
                "display_module_30":"把客户的需求变成可视化软件，设计 ",
                "display_module_31":"高效性和团队性的软件是我的职责。",
                "bottom_0":"魔法棒智能 为企业提供超过100个解决方案，客户需求，定制计划，过程研发，我们有非常完善的服务体系，最大化节省您的时间和成本，用最科学和最合理的方式给你一个满意的结果。",
                "bottom_1":"了解更多",
                "bottom_2": "用途链接",
                "bottom_3": "APP上线监控",
                "bottom_4":"自动机器翻译",
                "bottom_5":"安卓打包工具",
                "bottom_6":"批量后台管理",
                "bottom_7":"批量制图工具",
                "bottom_8":"关于公司",
                "bottom_9":"人工客服",
                "bottom_10":"证明信",
                "bottom_11":"问题帮助",
                "bottom_12": "联系我们",
                "bottom_13":"订阅我们",
                "bottom_14": "我们会定时为您推送我们的新项目和效率工具，发送邮箱地址即可订阅。",
                "bottom_15":"Copyright © 2010-2019 MagicWandAI.com 版权所有",
                "bottom_16": "帮助文档",
                "bottom_17":"隐私政策",
                "bottom_18":"服务条款"



            },
                                                                                //en_ch
            {
            "title":"team",
            "top_0":"Now enjoy 10% discount on consultation",
            "top_1":"Consult now",
            "top_2":"Get help",
            "top_3":"to introduce a job",
            "top_4":"information feedback",
            "top_5":"Language selection",
            "top_6":"Chinese",
            "top_7":"English",
            "top_8":"Japanese",
            "top_9":"Korean",
            "banner_0":"Zhongyu Love City, Yubei District, Chongqing",
            "banner_1":"China, Chongqing, Chongqing",
            "banner_2":"WeChat:",
            "banner_3":"18184079966",
            "banner_4":"Problem Help",
            "banner_5":"Home",
            "banner_6":"About the company",
            "banner_7":"Team Style",
            "banner_8":"contact us",
            "banner_9":"Home",
            "banner_10":"About the company",
            "banner_11":"Team style",
            "banner_12":"about us",
            "banner_13":"Team style",
            "banner_14":"Home",
            "banner_15":"about us",
            "banner_16":"Contact our Team",
            "banner_17":"share it",
            "display_module_0":"batistaqin",
            "display_module_1":"The design Architecture",
            "display_module_2":"For demand and technical feasibility",
            "display_module_3":"Design the optimal programming ideas.",
            "display_module_4":"Quyongje",
            "display_module_5":"The client designer",
            "display_module_6":"Design the most intuitive side to the customer",
            "display_module_7":"Address your needs in the most concise way.",
            "display_module_8":"Li Dong hai",
            "display_module_9":"The automation designer",
            "display_module_10":"Analyze all the steps and simplify them to one step",
            "display_module_11":"It is my responsibility to design an automated process.",
            "display_module_12":"Tan Hao",
            "display_module_13":"Cryptographic researcher",
            "display_module_14":"Keep data safe and private",
            "display_module_15":"Silently protect users from every security risk.",
            "display_module_16":"Hou Yao",
            "display_module_17":"Data Analyst",
            "display_module_18":"Obtain data analysis data design algorithm",
            "display_module_19":"Use algorithms, stability, efficiency, and intelligence.",
            "display_module_20":"Li Yaqing",
            "display_module_21":"project manager",
            "display_module_22":"Bridges between technicians and non-technical personnel",
            "display_module_23":"Give me the question and give you the solution",
            "display_module_24":"SiSuTing",
            "display_module_25":"Customer manager",
            "display_module_26":"Follow up internal and external project progress to understand customer needs",
            "display_module_27":"All the customer's questions must be answered.",
            "display_module_28":"ZhangYuanQi",
            "display_module_29":"Software designer",
            "display_module_30":"Turn customer requirements into visual software,",
            "display_module_31":"It is my responsibility to design software that is efficient and team oriented.",
            "bottom_0": "Magic Wand Intelligence for enterprises to provide more than 100 solutions, customer needs, customized plans, process research and development, we have a very perfect service system, to maximize the savings of your time and cost, in the most scientific and reasonable way to give you a satisfactory result.",
            "bottom_1": "Find out more about",
            "bottom_2": "Purpose links",
            "bottom_3": "APP on-line monitoring",
            "bottom_4": "Auto machine translation",
            "bottom_5": "Android Packaging Tools",
            "bottom_6": "Bulk  Management",
            "bottom_7": "Bulk Mapping Tools",
            "bottom_8": "About the company",
            "bottom_9": "Manual Customer Service",
            "bottom_10": "Letter",
            "bottom_11": "Problem Help",
            "bottom_12": "Contact Us",
            "bottom_13": "Subscribe to our",
            "bottom_14": "We will regularly push our new projects and efficiency tools for you, sending email addresses to subscribe.",
            "bottom_15": "Copyright © 2010-2019 MagicWandAI.com all rights reserved",
            "bottom_16": "Help documentation",
            "bottom_17": "Privacy Policy",
            "bottom_18": "Terms of Service"
        },

                                                                                //日语
            {
                "title":"チームスタイル",
                "top_0":"今相談の10％の割引を楽しみなさい",
                "top_1":"今相談する",
                "top_2":"ヘルプを表示する",
                "top_3":"雇用紹介",
                "top_4":"フィードバック",
                "top_5":"言語の選択",
                "top_6":"中国語",
                "top_7":"英語",
                "top_8":"日本語",
                "top_9":"朝鮮語",
                "banner_0":"重慶ラブシティ、重北、ube北区",
                "banner_1":"中国、重慶、重慶",
                "banner_2":"wechat：",
                "banner_3":"18184079966",
                "banner_4":"問題のヘルプ",
                "banner_5":"ホーム",
                "banner_6":"会社について",
                "banner_7":"チームスタイル",
                "banner_8":"お問い合わせ",
                "banner_9":"ホーム",
                "banner_10":"会社概要",
                "banner_11":"チームスタイル",
                "banner_12":"私達について",
                "banner_13":"チームスタイル",
                "banner_14":"ホーム",
                "banner_15":"私達について",
                "banner_16":"チームに問い合わせる",
                "banner_17":"共有する",
                "display_module_0":"バティスタッキン",
                "display_module_1":"設計アーキテクチャ",
                "display_module_2":"需要と技術的な実現可能性",
                "display_module_3":"最適なプログラミングのアイデアを設計する",
                "display_module_4":"Quyongje",
                "display_module_5":"クライアントデザイナー",
                "display_module_6":"顧客にとって最も直感的な面をデザインする",
                "display_module_7":"最も簡潔な方法であなたのニーズに対処します。",
                "display_module_8":"李東海",
                "display_module_9":"自動化デザイナー",
                "display_module_10":"すべてのステップを分析し、1つのステップに単純化する",
                "display_module_11":"自動化プロセスを設計するのは私の責任です。",
                "display_module_12":"タンウェイ",
                "display_module_13":"暗号研究者",
                "display_module_14":"データを安全かつ非公開にする",
                "display_module_15":"あらゆるセキュリティリスクからユーザーを黙って保護します。",
                "display_module_16":"ホウヤオ",
                "display_module_17":"データアナリスト",
                "display_module_18":"データ解析データ設計アルゴリズムを取得",
                "display_module_19":"アルゴリズム、安定性、効率性、およびインテリジェンスを使用します。",
                "display_module_20":"李雅慶",
                "display_module_21":"プロジェクトマネージャー",
                "display_module_22":"技術者と非技術的人員の橋渡し",
                "display_module_23":"私に質問をしてください",
                "display_module_24":"スティテイ",
                "display_module_25":"取引先の社長",
                "display_module_26":"内外プロジェクトにフォローアップして、お客様のニーズを把握します",
                "display_module_27":"すべての取引先の质问に答えることができます。",
                "display_module_28":"張元キ",
                "display_module_29":"ソフトウェア・デザイナー",
                "display_module_30":"顧客のニーズを可視化したソフトウェアを作り",
                "display_module_31":"効率的でチームワーク的なソフトウェアを設計するのが私の役割です。",
                "bottom_0":"マジックスティックスマートは100以上のソリューション、顧客のニーズ、カスタマイズされた計画、プロセス開発を企業に提供します、我々はあなたの最も科学的で合理的な方法であなたに満足を与えます。",
                "bottom_1":"もっと詳しく",
                "bottom_2":"目的リンク",
                "bottom_3":"APPオンライン監視",
                "bottom_4":"自動機械翻訳",
                "bottom_5":"アンドロイドパッケージングツール",
                "bottom_6":"バッチバックグラウンド管理",
                "bottom_7":"バッチチャート作成ツール",
                "bottom_8":"会社概要",
                "bottom_9":"手動カスタマーサービス",
                "bottom_10":"証明書",
                "bottom_11":"問題のヘルプ",
                "bottom_12":"お問い合わせ",
                "bottom_13":"私たちを購読する",
                "bottom_14":"私たちは定期的にあなたのための新しいプロジェクトと効率ツールをプッシュします, 購読する電子メールアドレスを送信.",
                "bottom_15":"著作権©2010-2019 MagicWandAI.comすべての権利予約",
                "bottom_16":"ヘルプ文書",
                "bottom_17":"プライバシーポリシー",
                "bottom_18":"利用規約"
            },

            {                                               //韩语
                "title":"팀스타일",
                "top_0":"상담시 10 % 할인",
                "top_1":"지금 문의",
                "top_2":"도움말 얻기",
                "top_3":"취업 소개",
                "top_4":"피드백",
                "top_5":"언어 선택",
                "top_6":"중국어",
                "top_7":"영어",
                "top_8":"일본어",
                "top_9":"한국어",
                "banner_0":"중경 러브 시티 (Zhongyu Love City), 충칭 유북 구",
                "banner_1":"중국, 충칭, 충칭",
                "banner_2":"미크롱 편지:",
                "banner_3":"18184079966",
                "banner_4":"문제 도움말",
                "banner_5":"홈",
                "banner_6":"회사 소개",
                "banner_7":"팀 스타일",
                "banner_8":"문의하기",
                "banner_9":"홈",
                "banner_10":"회사 소개",
                "banner_11":"팀 스타일",
                "banner_12":"회사 소개",
                "banner_13":"팀 스타일",
                "banner_14":"홈",
                "banner_15":"회사 소개",
                "banner_16":"팀에 문의",
                "banner_17":"공유",
                "display_module_0":"바트 스타 퀸",
                "display_module_1":"디자인 아키텍처",
                "display_module_2":"수요와 기술적 가능성",
                "display_module_3":"최적의 프로그래밍 아이디어를 디자인하십시오.",
                "display_module_4":"융 예",
                "display_module_5":"클라이언트 디자이너",
                "display_module_6":"고객에게 가장 직관적 인 설계",
                "display_module_7":"가장 간결한 방식으로 요구 사항을 해결 합니다.",
                "display_module_8":"리 동해",
                "display_module_9":"자동화 설계자",
                "display_module_10":"모든 단계를 분석 하 고 한 단계로 단순화",
                "display_module_11":"자동화 된 프로세스를 설계하는 것은 필자의 책임입니다.",
                "display_module_12":"단 웨이",
                "display_module_13":"암호화 연구원",
                "display_module_14":"데이터를 안전하고 비공개로 유지하십시오.",
                "display_module_15":"모든 보안 위험으로부터 사용자를 자동으로 보호합니다.",
                "display_module_16":"허우 야 오",
                "display_module_17":"데이터 분석가",
                "display_module_18":"데이터 분석 데이터 설계 알고리즘 확보",
                "display_module_19":"알고리즘, 안정성, 효율성 및 인텔리전스를 사용 합니다.",
                "display_module_20":"이 야경",
                "display_module_21":"프로젝트 관리자",
                "display_module_22":"기술자와 비 기술적인 인력 간의 교량",
                "display_module_23":"나에게 질문을주고 해결책을 준다.",
                "display_module_24":"쓰쑤팅 ",
                "display_module_25":"클라이언트 매니저",
                "display_module_26":"국내외 항목의 진도를 따라 고객의 요구를 파악하다",
                "display_module_27":"모든 고객 문제는 질문이 있을 때 반드시 답해야 한다.",
                "display_module_28":"장위안치",
                "display_module_29":"소프트웨어 디자이너",
                "display_module_30":"고객들의 요구를 시각화 소프트웨어로 변화시키고",
                "display_module_31":"고효율과 팀워크를 설계하는 것이 내 책임이다.",
                "bottom_0":"Magic Stick Smart는 100 가지가 넘는 솔루션, 고객 요구, 맞춤형 계획, 프로세스 개발을 제공하며, 시간과 비용을 최대화하여 매우 과학적이고 합리적인 방식으로 고객 만족을 제공합니다. ",
                "bottom_1":"더 알아보기",
                "bottom_2":"목적 링크",
                "bottom_3":"APP 온라인 모니터링",
                "bottom_4":"자동 기계 번역",
                "bottom_5":"안 드 로이드 패키징 도구",
                "bottom_6":"일괄 백그라운드 관리",
                "bottom_7":"배치 차트 작성 도구",
                "bottom_8":"회사 소개",
                "bottom_9":"수동 고객 서비스",
                "bottom_10":"증명서",
                "bottom_11":"문제 도움말",
                "bottom_12":"문의하기",
                "bottom_13":"우리에게 구독",
                "bottom_14":"우리는 정기적으로 새로운 프로젝트와 효율성 도구를 밀어 구독 할 이메일 주소를 보냅니다.",
                "bottom_15":"저작권 © 2010-2019 MagicWandAI.com 모든 권리 보유",
                "bottom_16":"도움말 문서",
                "bottom_17":"개인 정보 보호 정책",
                "bottom_18":"서비스 약관"
            },
            //////////////////////////////////////////关于公司翻译///////////////////////////////////////////////////
                                                                                //中文
            {
                "title":"关于公司",
                "top_0": "现在咨询享受9折优惠",
                "top_1":"立即咨询",
                "top_2":"获取帮助",
                "top_3": "职业介绍",
                "top_4":"信息反馈",
                "top_5": "语言选择",
                "top_6":"中文",
                "top_7": "English",
                "top_8": "日语",
                "top_9": "韩语",
                "banner_0":"重庆市渝北区中渝爱都会",
                "banner_1":"中国，重庆，重庆市",
                "banner_2":"微信：",
                "banner_3":"18184079966",
                "banner_4":"问题帮助",
                "banner_5":"首页",
                "banner_6":"关于公司",
                "banner_7":"团队风采",
                "banner_8":"联系我们",
                "banner_9":"首页",
                "banner_10":"关于公司",
                "banner_11":"团队风采",
                "banner_12":"关于我们",
                "banner_13":"关于公司",
                "banner_14":"首页",
                "banner_15":"关于我们",
                "banner_16":"联系我们团队",
                "banner_17":"分享",
                "about_0": "我们的目标很简单，给用户最简单最直接的解决方案",
                "about_1": "我们需要让用户感受到，软件定制和自动化编程没有那么复杂，最重要的目的是让用户以最简单的方式得到解决方案，让用户明白我们在干什么，我们要干什么。",
                "about_2":"我们以最简洁最透明的方式呈现给客户，人人皆可轻易的进入自动化时代，让时间变得更宝贵，让个人和企业专注于思考更需要重视的事情，希望通过高效率和高自动化的流程和服务，为社会发展尽自己的微薄之力。",
                "about_3": "覃于澎",
                "about_4":"高效",
                "about_5": "直面问题",
                "about_6":"专业",
                "about_7":"解决问题",
                "about_8": "透明",
                "about_9": "过程跟踪",
                "3_middle_modules_0":"只为最佳",
                "3_middle_modules_1":"为什么选择我们",
                "3_middle_modules_2":"守时守信",
                "3_middle_modules_3":"是我们公司服务的准则，这意味着你得到了最高效的解决方案。",
                "3_middle_modules_4":"经验丰富",
                "3_middle_modules_5":"我们是具有多年经验的行业专家，提供最全面的服务。",
                "3_middle_modules_6":"解决问题",
                "3_middle_modules_7":"是人类行为趋势的一个缩影，旨在提高我们公司的服务对消费者的有效性。",
                "display_module_0":"我们团队",
                "display_module_1":"团队成员",
                "display_module_2":"所有成员",
                "display_module_3":"覃于澎 ",
                "display_module_4":"设计架构",
                "display_module_5":"针对需求和技术可行性",
                "display_module_6":"设计出最优的程序设计思路。",
                "display_module_7":"曲永杰",
                "display_module_8":"客户端设计师",
                "display_module_9":"把最为直观的一面设计给客户",
                "display_module_10":"用最简明的方式解决您的需求。",
                "display_module_11":"李东海",
                "display_module_12":"自动化设计师",
                "display_module_13":"分析所有的步骤并把它们简化成一步",
                "display_module_14":"设计自动化流程是我的职责。",
                "display_module_15":"谭昊",
                "display_module_16":"加密研究员",
                "display_module_17":"保证数据的安全和隐私",
                "display_module_18":"默默为用户防范每一次安全隐患。",
                "bottom_0":"魔法棒智能 为企业提供超过100个解决方案，客户需求，定制计划，过程研发，我们有非常完善的服务体系，最大化节省您的时间和成本，用最科学和最合理的方式给你一个满意的结果。",
                "bottom_1":"了解更多",
                "bottom_2": "用途链接",
                "bottom_3": "APP上线监控",
                "bottom_4":"自动机器翻译",
                "bottom_5":"安卓打包工具",
                "bottom_6":"批量后台管理",
                "bottom_7":"批量制图工具",
                "bottom_8":"关于公司",
                "bottom_9":"人工客服",
                "bottom_10":"证明信",
                "bottom_11":"问题帮助",
                "bottom_12": "联系我们",
                "bottom_13":"订阅我们",
                "bottom_14": "我们会定时为您推送我们的新项目和效率工具，发送邮箱地址即可订阅。",
                "bottom_15":"Copyright © 2010-2019 MagicWandAI.com 版权所有",
                "bottom_16": "帮助文档",
                "bottom_17":"隐私政策",
                "bottom_18":"服务条款"


            },
                                                                                    //英语
            {
                "title":"About the company",
                "top_0":"Now enjoy 10% discount on consultation",
                "top_1":"Consult now",
                "top_2":"Get help",
                "top_3":"to introduce a job",
                "top_4":"information feedback",
                "top_5":"Language selection",
                "top_6":"Chinese",
                "top_7":"English",
                "top_8":"Japanese",
                "top_9":"Korean",
                "banner_0":"Zhongyu Love City, Yubei District, Chongqing",
                "banner_1":"China, Chongqing, Chongqing",
                "banner_2":"WeChat:",
                "banner_3":"18184079966",
                "banner_4":"Problem Help",
                "banner_5":"Home",
                "banner_6":"About the company",
                "banner_7":"Team Style",
                "banner_8":"contact us",
                "banner_9":"Home",
                "banner_10":"About the company",
                "banner_11":"Team style",
                "banner_12":"about us",
                "banner_13":"About the company",
                "banner_14":"Home",
                "banner_15":"about us",
                "banner_16":"Contact our Team",
                "banner_17":"share it",
                "about_0":"Our goal is simple, giving users the simplest and most direct solution.",
                "about_1":"We need to make users feel that software customization and automated programming are not so complex, and the most important purpose is to get users the solution in the simplest way to let them know what we are doing and what we are going to do.",
                "about_2":"We present to our customers in the most concise and transparent way, everyone can easily enter the era of automation, make time more valuable, let individuals and businesses focus on thinking more things that need to be valued, hope to be efficient and highly automated ",
                "about_3":"覃于澎",
                "about_4":"Efficient",
                "about_5":"Face the problem",
                "about_6":"profession",
                "about_7":"Troubleshoot problems",
                "about_8":"Transparent",
                "about_9":"Process tracking",
                "3_middle_modules_0":"Only for the best",
                "3_middle_modules_1":"Why choose us",
                "3_middle_modules_2":"Punctual and trustworthy",
                "3_middle_modules_3":"is the standard of our company's services, which means you get the most efficient solution.",
                "3_middle_modules_4":"Experience",
                "3_middle_modules_5":"We are industry experts with many years of experience and provide the most comprehensive service.",
                "3_middle_modules_6":"Troubleshoot problems",
                "3_middle_modules_7":"It is a microcosm of the trend of human behavior, designed to improve the effectiveness of our company's services to consumers.",
                "display_module_0":"Our team",
                "display_module_1":"Team members",
                "display_module_2":"All members",
                "display_module_3":"覃于澎",
                "display_module_4":"Design Architecture",
                "display_module_5":"For demand and technical feasibility",
                "display_module_6":"Design the optimal programming ideas.",
                "display_module_7":"Quyongje",
                "display_module_8":"Client designer",
                "display_module_9":"Design the most intuitive side to the customer",
                "display_module_10":"Address your needs in the most concise way.",
                "display_module_11":"Li Donghai",
                "display_module_12":"Automation designer",
                "display_module_13":"Analyze all the steps and simplify them to one step",
                "display_module_14":"It is my responsibility to design an automated process.",
                "display_module_15":"Tan Hao",
                "display_module_16":"Cryptographic researcher",
                "display_module_17":"Keep data safe and private",
                "display_module_18":"Silently protect users from every security risk.",
                "bottom_0":"Magic Wand Intelligence for enterprises to provide more than 100 solutions, customer needs, customized plans, process research and development, we have a very perfect service system, to maximize the savings of your time and cost, in the most scientific and reasonable way to give you a satisfactory result.",
                "bottom_1":"understand more",
                "bottom_2":"Use link",
                "bottom_3":"App Online Monitoring",
                "bottom_4":"Automatic machine translation",
                "bottom_5":"Android packaging tool",
                "bottom_6":"Bulk Background Management",
                "bottom_7":"Batch charting tool",
                "bottom_8":"About the company",
                "bottom_9":"Manual Customer Service",
                "bottom_10":"certificate",
                "bottom_11":"Problem help",
                "bottom_12":"Contact Us",
                "bottom_13":"Subscribe to us",
                "bottom_14":"We will regularly push you our new project and efficiency tools, and send an email address to subscribe.",
                "bottom_15":"copyright©2010-2019 magicwandai.com All rights reserved",
                "bottom_16":"Help document",
                "bottom_17":"Privacy Policy",
                "bottom_18":"Terms of Service"
            },
                                                                        //日语
            {
                "title":"会社概要",
                "top_0":"今相談の10％の割引を楽しみなさい",
                "top_1":"今相談する",
                "top_2":"ヘルプを表示する",
                "top_3":"雇用紹介",
                "top_4":"フィードバック",
                "top_5":"言語の選択",
                "top_6":"中国語",
                "top_7":"英語",
                "top_8":"日本語",
                "top_9":"朝鮮語",
                "banner_0":"重慶ラブシティ、重北、ube北区",
                "banner_1":"中国、重慶、重慶",
                "banner_2":"WeChat：",
                "banner_3":"18184079966",
                "banner_4":"問題のヘルプ",
                "banner_5":"ホーム",
                "banner_6":"会社について",
                "banner_7":"チームスタイル",
                "banner_8":"お問い合わせ",
                "banner_9":"ホーム",
                "banner_10":"会社概要",
                "banner_11":"チームスタイル",
                "banner_12":"私達について",
                "banner_13":"会社概要",
                "banner_14":"ホーム",
                "banner_15":"私達について",
                "banner_16":"チームに問い合わせる",
                "banner_17":"共有する",
                "about_0":"私たちの目標はシンプルで、ユーザーに最も簡単で直接的な解決策を提供することです。",
                "about_1":"ソフトウェアのカスタマイズや自動化されたプログラミングはあまり複雑ではなく、最も重要な目的は、ユーザーに、私たちが何をしているのか、何をしているのかを知らせるために、最も簡単にユーザにソリューションを入手させることです。",
                "about_2":"私たちは最も簡潔で透明な方法でお客様に提示し、誰もが簡単に自動化の時代に入り、時間をより価値のあるものにし、個人や企業に価値のあることを考えさせようとします。",
                "about_3":"おー",
                "about_4":"効率的",
                "about_5":"問題に直面する",
                "about_6":"プロ",
                "about_7":"問題のトラブルシューティング",
                "about_8":"透明な",
                "about_9":"プロセス追跡",
                "3_middle_modules_0":"最高の",
                "3_middle_modules_1":"なぜ私たちを選ぶの？",
                "3_middle_modules_2":"時間厳守で信頼できる",
                "3_middle_modules_3":"は、当社のサービスの標準であり、最も効率的なソリューションを得ることを意味します。",
                "3_middle_modules_4":"経験豊富",
                "3_middle_modules_5":"私たちは長年の経験を持つ業界の専門家であり、最も包括的なサービスを提供しています。",
                "3_middle_modules_6":"問題のトラブルシューティング",
                "3_middle_modules_7":"それは人間の行動の傾向の縮図であり、消費者に対する当社のサービスの有効性を改善するように設計されています。",
                "display_module_0":"私たちのチーム",
                "display_module_1":"チームメンバー",
                "display_module_2":"全メンバー",
                "display_module_3":"おー",
                "display_module_4":"設計アーキテクチャ",
                "display_module_5":"需要と技術的な実現可能性",
                "display_module_6":"最適なプログラミングのアイデアを設計する",
                "display_module_7":"Quyongje",
                "display_module_8":"クライアントデザイナー",
                "display_module_9":"顧客にとって最も直感的な面をデザインする",
                "display_module_10":"最も簡潔な方法であなたのニーズに対処します。",
                "display_module_11":"李東海",
                "display_module_12":"自動化デザイナー",
                "display_module_13":"すべてのステップを分析し、1つのステップに単純化する",
                "display_module_14":"自動化プロセスを設計するのは私の責任です。",
                "display_module_15":"タンウェイ",
                "display_module_16":"暗号研究者",
                "display_module_17":"データを安全かつ非公開にする",
                "display_module_18":"あらゆるセキュリティリスクからユーザーを黙って保護します。",
                "bottom_0":"100以上のソリューション、顧客のニーズ、カスタマイズされた計画、プロセス研究と開発を提供する企業のための魔法の杖の知性は、我々はあなたに満足のいく結果を与えるために、最も科学的かつ合理的な方法で、あなたの時間とコストの節約を最大化するために、非常に完璧なサービスシステムを持っています",
                "bottom_1":"もっと詳しく",
                "bottom_2":"リンクを使用",
                "bottom_3":"アプリのオンライン監視",
                "bottom_4":"自動機械翻訳",
                "bottom_5":"Androidのパッケージングツール",
                "bottom_6":"一括バックグラウンド管理",
                "bottom_7":"バッチチャート作成ツール",
                "bottom_8":"会社について",
                "bottom_9":"手動カスタマーサービス",
                "bottom_10":"証明書",
                "bottom_11":"問題の解決",
                "bottom_12":"お 問い合わせ",
                "bottom_13":"私たちを購読する",
                "bottom_14":"私たちは定期的にあなたに私たちの新しいプロジェクトと効率化ツールをプッシュして、購読するために電子メールアドレスを送ります。",
                "bottom_15":"著作権© 2010-2019 magicwandai.com すべての権利予約",
                "bottom_16":"ヘルプ文書",
                "bottom_17":"プライバシーポリシー",
                "bottom_18":"サービス利用規約"
            },
                                                                    //韩语
            {
                "title":"회사 소개",
                "top_0":"상담시 10 % 할인",
                "top_1":"지금 문의",
                "top_2":"도움말 얻기",
                "top_3":"취업 소개",
                "top_4":"피드백",
                "top_5":"언어 선택",
                "top_6":"중국어",
                "top_7":"영어",
                "top_8":"일본어",
                "top_9":"한국어",
                "banner_0":"중경 러브 시티 (Zhongyu Love City), 충칭 유북 구",
                "banner_1":"중국, 충칭, 충칭",
                "banner_2":"WeChat :",
                "banner_3":"18184079966",
                "banner_4":"문제 도움말",
                "banner_5":"홈",
                "banner_6":"회사 소개",
                "banner_7":"팀 스타일",
                "banner_8":"문의하기",
                "banner_9":"홈",
                "banner_10":"회사 소개",
                "banner_11":"팀 스타일",
                "banner_12":"회사 소개",
                "banner_13":"회사 소개",
                "banner_14":"홈",
                "banner_15":"회사 소개",
                "banner_16":"팀에 문의",
                "banner_17":"공유",
                "about_0":"우리의 목표는 간단하며 사용자에게 가장 단순하고 가장 직접적인 솔루션을 제공합니다.",
                "about_1":"우리는 사용자가 소프트웨어 맞춤화 및 자동화 된 프로그래밍이 그렇게 복잡 하지 않다는 것을 느끼게 해야 하며, 가장 중요 한 목적은 사용자가 우리가 무엇을 하 고 있고 무엇을 하 고 있는지 알려 주는 가장 간단한 방법으로 솔루션을 얻는 것입니다.",
                "about_2":"우리는 고객에게 가장 간결하고 투명한 방식으로 제시하여 모든 사람들이 쉽게 자동화의 시대에 접어 들며 시간을 더욱 가치있게 만들고 개인과 기업이 가치 있고 가치있는 일을 생각하고 효율적이고 고도로 자동화 될 수 있도록 노력할 것입니다 ",
                "about_3":"覃 于 ンプ",
                "about_4":"효율적인",
                "about_5":"문제에 직면",
                "about_6":"전문가",
                "about_7":"문제 해결",
                "about_8":"투명한",
                "about_9":"프로세스 추적",
                "3_middle_modules_0":"최고의",
                "3_middle_modules_1":"왜 우리를 선택합니까?",
                "3_middle_modules_2":"지키고 신뢰할 수있는",
                "3_middle_modules_3":"우리 회사의 서비스의 표준, 즉 당신은 가장 효율적인 솔루션을 얻을 수 있습니다.",
                "3_middle_modules_4":"숙련 된",
                "3_middle_modules_5":"우리는 다년간의 경험을 가진 업계 전문가이며 가장 포괄적 인 서비스를 제공합니다.",
                "3_middle_modules_6":"문제 해결",
                "3_middle_modules_7":"그것은 우리의 회사 서비스의 효율성을 소비자들에게 향상시키기 위해 고안된 인간 행동의 추세에 대한 소우주입니다.",
                "display_module_0":"우리 팀",
                "display_module_1":"팀 구성원",
                "display_module_2":"모든 회원",
                "display_module_3":"覃 于 ンプ",
                "display_module_4":"디자인 아키텍처",
                "display_module_5":"수요와 기술적 가능성",
                "display_module_6":"최적의 프로그래밍 아이디어를 디자인하십시오.",
                "display_module_7":"융 예",
                "display_module_8":"클라이언트 디자이너",
                "display_module_9":"고객에게 가장 직관적 인 설계",
                "display_module_10":"가장 간결한 방식으로 요구 사항을 해결 합니다.",
                "display_module_11":"리 동해",
                "display_module_12":"자동화 설계자",
                "display_module_13":"모든 단계를 분석 하 고 한 단계로 단순화",
                "display_module_14":"자동화 된 프로세스를 설계하는 것은 필자의 책임입니다.",
                "display_module_15":"단 웨이",
                "display_module_16":"암호화 연구원",
                "display_module_17":"데이터를 안전하고 비공개로 유지하십시오.",
                "display_module_18":"모든 보안 위험으로부터 사용자를 자동으로 보호합니다.",
                "bottom_0":"마술 지팡이 지능 기업이 100 이상의 솔루션, 고객 요구, 맞춤형 계획, 프로세스 연구 및 개발을 제공 하기 위해 우리는 매우 완벽 한 서비스 시스템을 갖추고 있어 가장 과학적이 고 합리적인 방법으로 만족 스러운 결과를 얻을 수 있는 시간과 비용 절감을 극대화 합니다.",
                "bottom_1":"더 알아보기",
                "bottom_2":"링크 사용",
                "bottom_3":"앱 온라인 모니터링",
                "bottom_4":"자동 기계 번역",
                "bottom_5":"안드로이드 포장 도구",
                "bottom_6":"대량 백그라운드 관리",
                "bottom_7":"배치 차트 작성 도구",
                "bottom_8":"회사 소개",
                "bottom_9":"수동 고객 서비스",
                "bottom_10":"증명서",
                "bottom_11":"문제 도움말",
                "bottom_12":"문의",
                "bottom_13":"우리에게 구독",
                "bottom_14":"우리는 정기적으로 새로운 프로젝트 및 효율성 도구를 제공하고 구독 할 전자 메일 주소를 보냅니다.",
                "bottom_15":"저작권 © 2010-2019 magicwandai.com 판권 소유",
                "bottom_16":"도움말 문서",
                "bottom_17":"개인 정보 보호 정책",
                "bottom_18":"서비스 약관"
            },


            //////////////////////////////////////////联系我们翻译///////////////////////////////////////////////////

                                                                        //中文
            {
                "title":"联系我们",
                "top_0": "现在咨询享受9折优惠",
                "top_1":"立即咨询",
                "top_2":"获取帮助",
                "top_3": "职业介绍",
                "top_4":"信息反馈",
                "top_5": "语言选择",
                "top_6":"中文",
                "top_7": "English",
                "top_8": "日语",
                "top_9": "韩语",
                "banner_0":"重庆市渝北区中渝爱都会",
                "banner_1":"中国，重庆，重庆市",
                "banner_2":"微信：",
                "banner_3":"18184079966",
                "banner_4":"问题帮助",
                "banner_5":"首页",
                "banner_6":"关于公司",
                "banner_7":"团队风采",
                "banner_8":"联系我们",
                "banner_9":"首页",
                "banner_10":"关于公司",
                "banner_11":"团队风采",
                "banner_12":"联系我们",
                "banner_13":"联系我们",
                "banner_14":"首页",
                "banner_15":"联系我们",
                "banner_16":"分享",
                "contact_0":"立即联系",
                "contact_1":"直接说明您的需求",
                "contact_2":"我们公司为企业提供超过100个解决方案，服务需求，定制计划，过程研发，我们有非常完善的服务体系，最大化节省您的时间和成本，用最科学和最合理的方式给你一个满意的结果。",
                "contact_3":"选择服务",
                "contact_4":"解决方案咨询",
                "contact_5":"软件工具定制",
                "contact_6":"网络数据获取",
                "contact_7":"新的合作需求",
                "contact_8":"其他意外惊喜",
                "contact_9":"点击发送",
                "contact_10":"公司地址",
                "contact_11":"地址：",
                "contact_12":"中国，重庆，重庆市",
                "contact_13":"渝北区，中渝爱都会写字楼3幢25-2",
                "contact_14":"微信：",
                "contact_15":"+86 18184079966",
                "contact_16":"邮箱联系：",
                "contact_17":"qin@east2west.cn"

            },
                                                                       //英语
            {
                "title":"about us",
                "top_0":"90 percent discount on consulting now",
                "top_1":"Consult now",
                "top_2":"Get help",
                "top_3":"Career Introduction",
                "top_4":"information feedback",
                "top_5":"language selection",
                "top_6":"Chinese",
                "top_7":"English",
                "top_8":"Japanese",
                "top_9":"Korean",
                "banner_0":"Chongqing, Chongqing,China ",
                "banner_1":"Zhongyu Love City, Yubei District, Chongqing",
                "banner_2":"Wechat:",
                "banner_3":"18184079966",
                "banner_4":"Problem help",
                "banner_5":"Home",
                "banner_6":"About the company",
                "banner_7":"Team style",
                "banner_8":"Contact Us",
                "banner_9":"Home",
                "banner_10":"About the company",
                "banner_11":"Team Style",
                "banner_12":"contact us",
                "banner_13":"Contact us",
                "banner_14":"Home",
                "banner_15":"Contact us",
                "banner_16":"share it",
                "contact_0":"Contact now",
                "contact_1":"Directly explain your needs",
                "contact_2":"Our company provides more than 100 solutions, service requirements, customized plans, process development, and we have a very complete service system to maximize your time and cost, and give you a satisfactory in the most scientific and reasonable way. ",
                "contact_3":"Select a service",
                "contact_4":"Solution consulting",
                "contact_5":"Software tool customization",
                "contact_6":"Network data acquisition",
                "contact_7":"New cooperation needs",
                "contact_8":"Other surprises",
                "contact_9":"Click Send",
                "contact_10":"company address",
                "contact_11":"address:",
                "contact_12":"China, Chongqing, Chongqing",
                "contact_13":"Yubei District, Zhonghao Ai Metropolis Office Building 3 25-2",
                "contact_14":"WeChat:",
                "contact_15":"+86 18184079966",
                "contact_16":"Email contact:",
                "contact_17":"Pro @east2west.才",
                "bottom_0":"Magic Wand Intelligence for enterprises to provide more than 100 solutions, customer needs, customized plans, process research and development, we have a very perfect service system, to maximize the savings of your time and cost, in the most scientific and reasonable way to give you a satisfactory result.",
                "bottom_1":"understand more",
                "bottom_2":"Use link",
                "bottom_3":"App Online Monitoring",
                "bottom_4":"Automatic machine translation",
                "bottom_5":"Android packaging tool",
                "bottom_6":"Bulk Background Management",
                "bottom_7":"Batch charting tool",
                "bottom_8":"About the company",
                "bottom_9":"Manual Customer Service",
                "bottom_10":"certificate",
                "bottom_11":"Problem help",
                "bottom_12":"Contact Us",
                "bottom_13":"Subscribe to us",
                "bottom_14":"We will regularly push you our new project and efficiency tools, and send an email address to subscribe.",
                "bottom_15":"copyright©2010-2019 magicwandai.com All rights reserved",
                "bottom_16":"Help document",
                "bottom_17":"Privacy Policy",
                "bottom_18":"Terms of Service"
            },
                                                                         //日语
            {
                "title":"私達について",
                "top_0":"今すぐコンサルティングの 90% 割引",
                "top_1":"今相談する",
                "top_2":"助けを得る",
                "top_3":"キャリア紹介",
                "top_4":"フィードバック",
                "top_5":"言語選択",
                "top_6":"中国語",
                "top_7":"英語",
                "top_8":"日本語",
                "top_9":"韓国語",
                "banner_0":"重慶ラブシティ、重北、ube北区",
                "banner_1":"中国、重慶、重慶",
                "banner_2":"Wechat：",
                "banner_3":"18184079966",
                "banner_4":"問題の解決",
                "banner_5":"ホーム",
                "banner_6":"会社について",
                "banner_7":"チームスタイル",
                "banner_8":"お 問い合わせ",
                "banner_9":"ホーム",
                "banner_10":"会社について",
                "banner_11":"チームスタイル",
                "banner_12":"お問い合わせ",
                "banner_13":"我々に連絡する",
                "banner_14":"ホーム",
                "banner_15":"我々に連絡する",
                "banner_16":"共有する",
                "contact_0":"今すぐお問い合わせ",
                "contact_1":"あなたのニーズを直接説明する",
                "contact_2":"私達の会社は100以上の解決、サービス要求、カスタマイズされた計画、プロセス開発を提供し、私達はあなたの時間および費用を最大にし、最も科学的かつ合理的な方法であなたに満足を与える非常に完全なサービスシステムを有する。",
                "contact_3":"サービスの選択",
                "contact_4":"ソリューションコンサルティング",
                "contact_5":"ソフトウェアツールのカスタマイズ",
                "contact_6":"ネットワークデータの取得",
                "contact_7":"新たな協力ニーズ",
                "contact_8":"その他の驚き",
                "contact_9":"送信をクリックし",
                "contact_10":"会社の住所",
                "contact_11":"住所：",
                "contact_12":"中国、重慶、重慶",
                "contact_13":"ube北区、中華愛メトロポリス事務所ビル3 25-2",
                "contact_14":"WeChat：",
                "contact_15":"+ 86 18184079966",
                "contact_16":"メール連絡先：",
                "contact_17":"Pro @ east2west",
                "bottom_0":"100以上のソリューション、顧客のニーズ、カスタマイズされた計画、プロセス研究と開発を提供する企業のための魔法の杖の知性は、我々はあなたに満足のいく結果を与えるために、最も科学的かつ合理的な方法で、あなたの時間とコストの節約を最大化するために、非常に完璧なサービスシステムを持っています",
                "bottom_1":"もっと詳しく",
                "bottom_2":"リンクを使用",
                "bottom_3":"アプリのオンライン監視",
                "bottom_4":"自動機械翻訳",
                "bottom_5":"Androidのパッケージングツール",
                "bottom_6":"一括バックグラウンド管理",
                "bottom_7":"バッチチャート作成ツール",
                "bottom_8":"会社について",
                "bottom_9":"手動カスタマーサービス",
                "bottom_10":"証明書",
                "bottom_11":"問題の解決",
                "bottom_12":"お 問い合わせ",
                "bottom_13":"私たちを購読する",
                "bottom_14":"私たちは定期的にあなたに私たちの新しいプロジェクトと効率化ツールをプッシュして、購読するために電子メールアドレスを送ります。",
                "bottom_15":"著作権© 2010-2019 magicwandai.com すべての権利予約",
                "bottom_16":"ヘルプ文書",
                "bottom_17":"プライバシーポリシー",
                "bottom_18":"サービス利用規約"
            },
                                                                            //韩语
            {
                "title":"회사 소개",
                "top_0":"90% 할인에 대 한 컨설팅 지금",
                "top_1":"지금 문의",
                "top_2":"도움 받기",
                "top_3":"커리어 소개",
                "top_4":"피드백",
                "top_5":"언어 선택",
                "top_6":"중국어",
                "top_7":"영어",
                "top_8":"일본어",
                "top_9":"한국어",
                "banner_0":"중경 러브 시티 (Zhongyu Love City), 충칭 유북 구",
                "banner_1":"중국, 충칭, 충칭",
                "banner_2":"Wechat:",
                "banner_3":"18184079966",
                "banner_4":"문제 도움말",
                "banner_5":"홈",
                "banner_6":"회사 소개",
                "banner_7":"팀 스타일",
                "banner_8":"문의",
                "banner_9":"홈",
                "banner_10":"회사 소개",
                "banner_11":"팀 스타일",
                "banner_12":"문의하기",
                "banner_13":"우리에게 연락하다",
                "banner_14":"홈",
                "banner_15":"우리에게 연락하다",
                "banner_16":"공유",
                "contact_0":"지금 연락 하기",
                "contact_1":"필요 사항을 직접 설명하십시오.",
                "contact_2":"당사는 100 가지 이상의 솔루션, 서비스 요구 사항, 맞춤형 계획, 프로세스 개발을 제공하며 시간과 비용을 최대화하고 가장 과학적이고 합리적인 방식으로 만족할만한 서비스 시스템을 갖추고 있습니다. ",
                "contact_3":"서비스를 선택",
                "contact_4":"솔루션 컨설팅",
                "contact_5":"소프트웨어 도구 사용자 정의",
                "contact_6":"네트워크 데이터 수집",
                "contact_7":"새로운 협력 요구",
                "contact_8":"기타 놀라움",
                "contact_9":"보내기를 클릭",
                "contact_10":"회사 주소",
                "contact_11":"주소 :",
                "contact_12":"중국, 충칭, 충칭",
                "contact_13":"중부 아이오와 유북 구청 3 25-2",
                "contact_14":"WeChat :",
                "contact_15":"+ 86 18184079966",
                "contact_16":"이메일 문의 :",
                "contact_17":"Pro @ east2west. 才",
                "bottom_0":"마술 지팡이 지능 기업이 100 이상의 솔루션, 고객 요구, 맞춤형 계획, 프로세스 연구 및 개발을 제공 하기 위해 우리는 매우 완벽 한 서비스 시스템을 갖추고 있어 가장 과학적이 고 합리적인 방법으로 만족 스러운 결과를 얻을 수 있는 시간과 비용 절감을 극대화 합니다.",
                "bottom_1":"더 알아보기",
                "bottom_2":"링크 사용",
                "bottom_3":"앱 온라인 모니터링",
                "bottom_4":"자동 기계 번역",
                "bottom_5":"안드로이드 포장 도구",
                "bottom_6":"대량 백그라운드 관리",
                "bottom_7":"배치 차트 작성 도구",
                "bottom_8":"회사 소개",
                "bottom_9":"수동 고객 서비스",
                "bottom_10":"증명서",
                "bottom_11":"문제 도움말",
                "bottom_12":"문의",
                "bottom_13":"우리에게 구독",
                "bottom_14":"우리는 정기적으로 새로운 프로젝트 및 효율성 도구를 제공하고 구독 할 전자 메일 주소를 보냅니다.",
                "bottom_15":"저작권 © 2010-2019 magicwandai.com 판권 소유",
                "bottom_16":"도움말 문서",
                "bottom_17":"개인 정보 보호 정책",
                "bottom_18":"서비스 약관"
            }





        ];

//首页///////////////////////////////////////////////////////////////////////////////////////////////////
    $(".btn0").click(function() {

        $('.home').each(function (index, ele){

            $(this).text(language[0][$(this).attr('data-change')]);   //中文

        });
        $('title').html('首页');
    });

    $(".btn1").click(function() {
        $('.home').each(function (index, ele){

            $(this).text(language[1][$(this).attr('data-change')]);      //英文

        });
        $('title').html('Home');
    });

    $(".btn2").click(function() {
        $('.home').each(function (index, ele){

            $(this).text(language[2][$(this).attr('data-change')]);      //日语

        });
        $('title').html('ホームページ');
    });

    $(".btn3").click(function() {
        $('.home').each(function (index, ele){

            $(this).text(language[3][$(this).attr('data-change')]);      //韩语

        });
        $('title').html('홈페이지');
    });


    //团队风采///////////////////////////////////////////////////////////////////////////////////////////////////

    $(".btn4").click(function() {

        $('.team').each(function (index, ele){

            $(this).text(language[4][$(this).attr('data-change')]);   //中文

        });

        $('title').html('团队风采');
    });

    $(".btn5").click(function() {

        $('.team').each(function (index, ele){

            $(this).text(language[5][$(this).attr('data-change')]);   //英语

        });

        $('title').html('team');
    });


    $(".btn6").click(function() {

        $('.team').each(function (index, ele){

            $(this).text(language[6][$(this).attr('data-change')]);   //日语

        });

        $('title').html('チームスタイル');
    });

    $(".btn7").click(function() {

        $('.team').each(function (index, ele){

            $(this).text(language[7][$(this).attr('data-change')]);   //韩语

        });

        $('title').html('팀스타일');
    });



    /////////////关于公司//////////////////////

    $(".btn8").click(function() {

        $('.about').each(function (index, ele){

            $(this).text(language[8][$(this).attr('data-change')]);   //中文

        });

        $('title').html('关于公司');
    });

    $(".btn9").click(function() {

        $('.about').each(function (index, ele){

            $(this).text(language[9][$(this).attr('data-change')]);   //英语

        });

        $('title').html('team');
    });


    $(".btn10").click(function() {

        $('.about').each(function (index, ele){

            $(this).text(language[10][$(this).attr('data-change')]);   //日语

        });

        $('title').html('チームスタイル');
    });

    $(".btn11").click(function() {

        $('.about').each(function (index, ele){

            $(this).text(language[11][$(this).attr('data-change')]);   //韩语

        });

        $('title').html('팀스타일');
    });


    /////////////关于我们//////////////////////

    $(".btn12").click(function() {

        $('.contact').each(function (index, ele){

            $(this).text(language[12][$(this).attr('data-change')]);   //中文

        });

        $('title').html('关于我们');
    });

    $(".btn13").click(function() {

        $('.contact').each(function (index, ele){

            $(this).text(language[13][$(this).attr('data-change')]);   //英语

        });

        $('title').html('about us');
    });


    $(".btn14").click(function() {

        $('.contact').each(function (index, ele){

            $(this).text(language[14][$(this).attr('data-change')]);   //日语

        });

        $('title').html('私たちについて');
    });

    $(".btn15").click(function() {

        $('.contact').each(function (index, ele){

            $(this).text(language[15][$(this).attr('data-change')]);   //韩语

        });

        $('title').html('우리가 어떻게');
    });
});
